ARG PHP_VERSION=8.4
FROM dunglas/frankenphp:1.9-php${PHP_VERSION}

RUN install-php-extensions \
    bcmath \
    exif \
    gd \
    intl \
    mbstring \
    mysqli \
    opcache \
    pdo_mysql \
    zip \
    curl \
    xml \
    dom \
    simplexml \
    tokenizer \
    json \
    fileinfo \
    sockets \
    imagick
